1.取消强制指定gbk字符集(会导致在git拉取之后出现乱码)
Lixeer/ChatRetransmission-ACS pull request #2
Opened 2023-03-25 02:00 UTC by chuanzhubin

1.取消强制指定gbk字符集(会导致在git拉取之后出现乱码)
2.从环境变量中读取OPENAI_API_KEY

2023-03-25 02:16 UTC, Lixeer commented
好的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月25日(周六) 上午10:01
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Lixeer/ChatRetransmission-ACS] 1.取消强制指定gbk字符集(会导致在git拉取之后出现乱码) (PR #2)



1.取消强制指定gbk字符集(会导致在git拉取之后出现乱码)
 2.从环境变量中读取OPENAI_API_KEY
 
 
You can view, comment on, or merge this pull request online at:
 
&nbsp;&nbsp;https://github.com/Lixeer/ChatRetransmission-ACS/pull/2
 
Commit Summary
    
67caf96  1.取消强制指定gbk字符集(会导致在git拉取之后出现乱码)
  
File Changes 
 
(2&nbsp;files)
    
     M     S-main.py     (5)   
   
     M     client.py     (15)   
  
Patch Links:
    
https://github.com/Lixeer/ChatRetransmission-ACS/pull/2.patch
   
https://github.com/Lixeer/ChatRetransmission-ACS/pull/2.diff
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

2023-03-25 10:40 UTC, Lixeer commented
已修改 感谢反馈 请再次pr&nbsp;



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月25日(周六) 上午10:01
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Lixeer/ChatRetransmission-ACS] 1.取消强制指定gbk字符集(会导致在git拉取之后出现乱码) (PR #2)



1.取消强制指定gbk字符集(会导致在git拉取之后出现乱码)
 2.从环境变量中读取OPENAI_API_KEY
 
 
You can view, comment on, or merge this pull request online at:
 
&nbsp;&nbsp;https://github.com/Lixeer/ChatRetransmission-ACS/pull/2
 
Commit Summary
    
67caf96  1.取消强制指定gbk字符集(会导致在git拉取之后出现乱码)
  
File Changes 
 
(2&nbsp;files)
    
     M     S-main.py     (5)   
   
     M     client.py     (15)   
  
Patch Links:
    
https://github.com/Lixeer/ChatRetransmission-ACS/pull/2.patch
   
https://github.com/Lixeer/ChatRetransmission-ACS/pull/2.diff
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

2023-03-26 04:03 UTC, RobertIndie requested changes

2023-03-26 04:03 UTC, RobertIndie commented on client.py
> +    #�û���Ϣ����
注释编码格式不对，乱码了。

2023-03-26 07:57 UTC, Lixeer commented
到时改成英文
感谢反馈

---原始邮件---
发件人: "Zike ***@***.***&gt;
发送时间: 2023年3月26日(周日) 中午12:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Lixeer/ChatRetransmission-ACS] 1.取消强制指定gbk字符集(会导致在git拉取之后出现乱码) (PR #2)




 
@RobertIndie requested changes on this pull request.
 
 
In client.py:
 &gt; +    msg:���ڹ����û��ظ�����      ''' -    #用户信息工厂 +    #�û���Ϣ����  
注释编码格式不对，乱码了。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;

2023-03-26 08:05 UTC, chuanzhubin commented
好的. 这个PR先关了吧

2023-03-26 08:05 UTC, closed without merging

2023-03-26 08:08 UTC, Lixeer commented
好



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月26日(周日) 下午4:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Lixeer/ChatRetransmission-ACS] 1.取消强制指定gbk字符集(会导致在git拉取之后出现乱码) (PR #2)




 
好的. 这个PR先关了吧
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;